---
title: "Impatiens glandulifera seed morphometrics"
author: "James Hardwick"
date: "2024-12-10"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

```

## R Markdown

```{r libraries}
library(tidyverse)
library(cowplot)
library(RColorBrewer)

setwd('C:/Users/jahar/Documents/Seed_transport_py/R_analysis/INNS_seed_transport/')
```

# import data
```{r import and tidy data}
# seed morphology data 
seed_morphology_raw <- read_csv("data/seed_morphology_raw.csv")

seed_morphology <-seed_morphology_raw %>%
  group_by(group) %>%
  filter(length < 7.5) %>%
  summarise(mean_length_cm = mean(length)/10,
            mean_width_cm = mean(width)/10,
            mean_area_cm2 = mean(area)/10,
            mean_circularity = mean(circularity),
            mean_solidity = mean(solidity)) %>%
  mutate(group = tolower(group))

# seed mass data 
seed_mass <- read_csv("data/seed_mass.csv") %>%
  group_by(group)%>%
  summarise(mean_mass_g = mean(mass_g),
            mean_mass_mg = mean(mass_mg)) %>%
  mutate(group = tolower(group))

morph_mass <- seed_morphology %>%
  full_join(seed_mass, by = "group")

# seed settling velocity data 
seed_ws <- read_csv("data/seed_ws.csv", col_types = cols(...1 = col_skip())) 
  
seed_ws <- seed_ws %>%
  mutate(group = tolower(group))

```

# calcualte other morphometric variables and join with Ws
```{r morphometrics}

seed_morphometrics <- morph_mass %>%
 mutate(volume_cm3 = (4/3 * pi * (mean_width_cm/3)^3),
         density_gcm3 = mean_mass_g/volume_cm3,
         density_gcm3= if_else(density_gcm3 > 8, 
                                    density_gcm3 - (density_gcm3 * 0.95), density_gcm3))

```

```{r morph mass Ws}
ws_morph_mass <- morph_mass  %>%
  full_join(seed_ws, by ='group')
```

